@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTIxMDc1NTh9.e-bzL2TAODMWQg8Ve1RktR_RpyKkoBTHe7jpYAtVquc

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "user_name": "Bunell5090",
  "first_name": "Ben",
  "last_name": "Unell",
  "email": "Bunell5090@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Customers create
POST http://localhost:3000/customers
Content-Type: application/json

{
"first_name": "Chani",
"last_name": "Unell",
"address": "940 W. Gordon Terrace",
"city_state": "Chicago, IL",
"zipcode": "60613"
}

### Pets create
POST http://localhost:3000/pets
Content-Type: application/json

{
"name": "Chloe",
"customer_id": 1,
"species": "Dog",
"breed": "Maltipoo",
"birthday": "06-06-2020",
"sex": "Female",
"sterilized": true
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "user_name": "Bunell5090",
  "password": "password"
}